set(_CATKIN_CURRENT_PACKAGE "volumetric_drilling_msgs")
set(volumetric_drilling_msgs_VERSION "0.0.0")
set(volumetric_drilling_msgs_MAINTAINER "adnan <amunawar@wpi.edu>")
set(volumetric_drilling_msgs_PACKAGE_FORMAT "1")
set(volumetric_drilling_msgs_BUILD_DEPENDS "geometry_msgs" "std_msgs" "message_generation")
set(volumetric_drilling_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "std_msgs" "message_runtime")
set(volumetric_drilling_msgs_BUILDTOOL_DEPENDS "catkin")
set(volumetric_drilling_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(volumetric_drilling_msgs_EXEC_DEPENDS "geometry_msgs" "std_msgs" "message_runtime")
set(volumetric_drilling_msgs_RUN_DEPENDS "geometry_msgs" "std_msgs" "message_runtime")
set(volumetric_drilling_msgs_TEST_DEPENDS )
set(volumetric_drilling_msgs_DOC_DEPENDS )
set(volumetric_drilling_msgs_URL_WEBSITE "")
set(volumetric_drilling_msgs_URL_BUGTRACKER "")
set(volumetric_drilling_msgs_URL_REPOSITORY "")
set(volumetric_drilling_msgs_DEPRECATED "")